@startuml C2_Containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(admin, "Power User")
Person(user1, "Regular User")

System_Boundary(c1, "P1_AnalyzeTrades") {
    Container(backend, "Backend Local Scripts", "Python", "...a-g.ipynb")
    Container(frontend, "Frontend Online App", "Python", "(streamlit) app")
    Container(models, "Model Folder/Database", "MLFlow/Python")
}
Rel(admin, backend, "Runs scripts", "using IDE, trade log")
Rel(backend, admin, "Estimated return, fitted/selected models")
Rel(backend, models, "Saves model to MLFlow")

Rel(user1, frontend, "Send inputs", "website")
Rel(frontend, user1, "Estimated return", "website")
Rel(models,frontend , "Pulls Model from MLFlow")
@enduml
